server:
  port: 8000
spring:
  redis:
    port: 6379
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: SCWPROJECT
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/offcn/project/mapper/*.xml
eureka:
  instance:
    prefer-ip-address: true
    appname: SCWPROJECT
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  bucketDomain: offcn20201001.oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4GCo6TpSag2SNq34CFo6
  accessKeySecret: 1VMd21yCJtOCsxXIDtaYsmLvnLGAij
  bucketName: offcn20201001